
export const USER_REGISTER_BEGIN = "USER_REGISTER_BEGIN"
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"

export const USER_LOGIN_BEGIN = "USER_LOGIN_BEGIN"
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"

export const LOGOUT = "LOGOUT"
